magick composite bot/Sdul_a00.png.png mid/Sdul_a00.png.png out.png
magick composite out.png top/Sdul_a00.png.png out.png
magick composite out.png Sdul.png out/Sdul_a00.png.png
magick composite bot/Sdul_a01.png.png mid/Sdul_a01.png.png out.png
magick composite out.png top/Sdul_a01.png.png out.png
magick composite out.png Sdul.png out/Sdul_a01.png.png
magick composite bot/Sdul_a02.png.png mid/Sdul_a02.png.png out.png
magick composite out.png top/Sdul_a02.png.png out.png
magick composite out.png Sdul.png out/Sdul_a02.png.png
magick composite bot/Sdul_a03.png.png mid/Sdul_a03.png.png out.png
magick composite out.png top/Sdul_a03.png.png out.png
magick composite out.png Sdul.png out/Sdul_a03.png.png
magick composite bot/Sdul_a04.png.png mid/Sdul_a04.png.png out.png
magick composite out.png top/Sdul_a04.png.png out.png
magick composite out.png Sdul.png out/Sdul_a04.png.png
magick composite bot/Sdul_b00.png.png mid/Sdul_b00.png.png out.png
magick composite out.png top/Sdul_b00.png.png out.png
magick composite out.png Sdul.png out/Sdul_b00.png.png
magick composite bot/Sdul_b01.png.png mid/Sdul_b01.png.png out.png
magick composite out.png top/Sdul_b01.png.png out.png
magick composite out.png Sdul.png out/Sdul_b01.png.png
magick composite bot/Sdul_b02.png.png mid/Sdul_b02.png.png out.png
magick composite out.png top/Sdul_b02.png.png out.png
magick composite out.png Sdul.png out/Sdul_b02.png.png
magick composite bot/Sdul_b03.png.png mid/Sdul_b03.png.png out.png
magick composite out.png top/Sdul_b03.png.png out.png
magick composite out.png Sdul.png out/Sdul_b03.png.png
magick composite bot/Sdul_b04.png.png mid/Sdul_b04.png.png out.png
magick composite out.png top/Sdul_b04.png.png out.png
magick composite out.png Sdul.png out/Sdul_b04.png.png
magick composite bot/Sdul_b05.png.png mid/Sdul_b05.png.png out.png
magick composite out.png top/Sdul_b05.png.png out.png
magick composite out.png Sdul.png out/Sdul_b05.png.png
magick composite bot/Sdul_b06.png.png mid/Sdul_b06.png.png out.png
magick composite out.png top/Sdul_b06.png.png out.png
magick composite out.png Sdul.png out/Sdul_b06.png.png
magick composite bot/Sdul_b07.png.png mid/Sdul_b07.png.png out.png
magick composite out.png top/Sdul_b07.png.png out.png
magick composite out.png Sdul.png out/Sdul_b07.png.png
magick composite bot/Sdul_b08.png.png mid/Sdul_b08.png.png out.png
magick composite out.png top/Sdul_b08.png.png out.png
magick composite out.png Sdul.png out/Sdul_b08.png.png
magick composite bot/Sdul_b09.png.png mid/Sdul_b09.png.png out.png
magick composite out.png top/Sdul_b09.png.png out.png
magick composite out.png Sdul.png out/Sdul_b09.png.png
magick composite bot/Sdul_b10.png.png mid/Sdul_b10.png.png out.png
magick composite out.png top/Sdul_b10.png.png out.png
magick composite out.png Sdul.png out/Sdul_b10.png.png
magick composite bot/Sdul_b11.png.png mid/Sdul_b11.png.png out.png
magick composite out.png top/Sdul_b11.png.png out.png
magick composite out.png Sdul.png out/Sdul_b11.png.png
magick composite bot/Sdul_c00.png.png mid/Sdul_c00.png.png out.png
magick composite out.png top/Sdul_c00.png.png out.png
magick composite out.png Sdul.png out/Sdul_c00.png.png
magick composite bot/Sdul_c01.png.png mid/Sdul_c01.png.png out.png
magick composite out.png top/Sdul_c01.png.png out.png
magick composite out.png Sdul.png out/Sdul_c01.png.png
magick composite bot/Sdul_c02.png.png mid/Sdul_c02.png.png out.png
magick composite out.png top/Sdul_c02.png.png out.png
magick composite out.png Sdul.png out/Sdul_c02.png.png
magick composite bot/Sdul_c03.png.png mid/Sdul_c03.png.png out.png
magick composite out.png top/Sdul_c03.png.png out.png
magick composite out.png Sdul.png out/Sdul_c03.png.png
magick composite bot/Sdul_c04.png.png mid/Sdul_c04.png.png out.png
magick composite out.png top/Sdul_c04.png.png out.png
magick composite out.png Sdul.png out/Sdul_c04.png.png
magick composite bot/Sdul_c05.png.png mid/Sdul_c05.png.png out.png
magick composite out.png top/Sdul_c05.png.png out.png
magick composite out.png Sdul.png out/Sdul_c05.png.png
magick composite bot/Sdul_c06.png.png mid/Sdul_c06.png.png out.png
magick composite out.png top/Sdul_c06.png.png out.png
magick composite out.png Sdul.png out/Sdul_c06.png.png
magick composite bot/Sdul_c07.png.png mid/Sdul_c07.png.png out.png
magick composite out.png top/Sdul_c07.png.png out.png
magick composite out.png Sdul.png out/Sdul_c07.png.png
magick composite bot/Sdul_c08.png.png mid/Sdul_c08.png.png out.png
magick composite out.png top/Sdul_c08.png.png out.png
magick composite out.png Sdul.png out/Sdul_c08.png.png
magick composite bot/Sdul_c09.png.png mid/Sdul_c09.png.png out.png
magick composite out.png top/Sdul_c09.png.png out.png
magick composite out.png Sdul.png out/Sdul_c09.png.png
magick composite bot/Sdul_d00.png.png mid/Sdul_d00.png.png out.png
magick composite out.png top/Sdul_d00.png.png out.png
magick composite out.png Sdul.png out/Sdul_d00.png.png
magick composite bot/Sdul_d01.png.png mid/Sdul_d01.png.png out.png
magick composite out.png top/Sdul_d01.png.png out.png
magick composite out.png Sdul.png out/Sdul_d01.png.png
magick composite bot/Sdul_d02.png.png mid/Sdul_d02.png.png out.png
magick composite out.png top/Sdul_d02.png.png out.png
magick composite out.png Sdul.png out/Sdul_d02.png.png
magick composite bot/Sdul_d03.png.png mid/Sdul_d03.png.png out.png
magick composite out.png top/Sdul_d03.png.png out.png
magick composite out.png Sdul.png out/Sdul_d03.png.png
magick composite bot/Sdul_d04.png.png mid/Sdul_d04.png.png out.png
magick composite out.png top/Sdul_d04.png.png out.png
magick composite out.png Sdul.png out/Sdul_d04.png.png
magick composite bot/Sdul_d05.png.png mid/Sdul_d05.png.png out.png
magick composite out.png top/Sdul_d05.png.png out.png
magick composite out.png Sdul.png out/Sdul_d05.png.png
magick composite bot/Sdul_d06.png.png mid/Sdul_d06.png.png out.png
magick composite out.png top/Sdul_d06.png.png out.png
magick composite out.png Sdul.png out/Sdul_d06.png.png
magick composite bot/Sdul_d07.png.png mid/Sdul_d07.png.png out.png
magick composite out.png top/Sdul_d07.png.png out.png
magick composite out.png Sdul.png out/Sdul_d07.png.png
magick composite bot/Sdul_d08.png.png mid/Sdul_d08.png.png out.png
magick composite out.png top/Sdul_d08.png.png out.png
magick composite out.png Sdul.png out/Sdul_d08.png.png
magick composite bot/Sdul_d09.png.png mid/Sdul_d09.png.png out.png
magick composite out.png top/Sdul_d09.png.png out.png
magick composite out.png Sdul.png out/Sdul_d09.png.png
magick composite bot/Sdul_d10.png.png mid/Sdul_d10.png.png out.png
magick composite out.png top/Sdul_d10.png.png out.png
magick composite out.png Sdul.png out/Sdul_d10.png.png
magick composite bot/Sdul_d11.png.png mid/Sdul_d11.png.png out.png
magick composite out.png top/Sdul_d11.png.png out.png
magick composite out.png Sdul.png out/Sdul_d11.png.png
magick composite bot/Sdul_d12.png.png mid/Sdul_d12.png.png out.png
magick composite out.png top/Sdul_d12.png.png out.png
magick composite out.png Sdul.png out/Sdul_d12.png.png
magick composite bot/Sdul_d13.png.png mid/Sdul_d13.png.png out.png
magick composite out.png top/Sdul_d13.png.png out.png
magick composite out.png Sdul.png out/Sdul_d13.png.png
magick composite bot/Sdul_d14.png.png mid/Sdul_d14.png.png out.png
magick composite out.png top/Sdul_d14.png.png out.png
magick composite out.png Sdul.png out/Sdul_d14.png.png
magick composite bot/Sdul_d15.png.png mid/Sdul_d15.png.png out.png
magick composite out.png top/Sdul_d15.png.png out.png
magick composite out.png Sdul.png out/Sdul_d15.png.png
magick composite bot/Sdul_d16.png.png mid/Sdul_d16.png.png out.png
magick composite out.png top/Sdul_d16.png.png out.png
magick composite out.png Sdul.png out/Sdul_d16.png.png
magick composite bot/Sdul_d17.png.png mid/Sdul_d17.png.png out.png
magick composite out.png top/Sdul_d17.png.png out.png
magick composite out.png Sdul.png out/Sdul_d17.png.png
magick composite bot/Sdul_d18.png.png mid/Sdul_d18.png.png out.png
magick composite out.png top/Sdul_d18.png.png out.png
magick composite out.png Sdul.png out/Sdul_d18.png.png
magick composite bot/Sdul_d19.png.png mid/Sdul_d19.png.png out.png
magick composite out.png top/Sdul_d19.png.png out.png
magick composite out.png Sdul.png out/Sdul_d19.png.png
magick composite bot/Sdul_d20.png.png mid/Sdul_d20.png.png out.png
magick composite out.png top/Sdul_d20.png.png out.png
magick composite out.png Sdul.png out/Sdul_d20.png.png
magick composite bot/Sdul_d21.png.png mid/Sdul_d21.png.png out.png
magick composite out.png top/Sdul_d21.png.png out.png
magick composite out.png Sdul.png out/Sdul_d21.png.png
magick composite bot/Sdul_d22.png.png mid/Sdul_d22.png.png out.png
magick composite out.png top/Sdul_d22.png.png out.png
magick composite out.png Sdul.png out/Sdul_d22.png.png
magick composite bot/Sdul_d23.png-001.png mid/Sdul_d23.png-001.png out.png
magick composite out.png top/Sdul_d23.png-001.png out.png
magick composite out.png Sdul.png out/Sdul_d23.png-001.png
magick composite bot/Sdul_d23.png-002.png mid/Sdul_d23.png-002.png out.png
magick composite out.png top/Sdul_d23.png-002.png out.png
magick composite out.png Sdul.png out/Sdul_d23.png-002.png
magick composite bot/Sdul_d23.png-003.png mid/Sdul_d23.png-003.png out.png
magick composite out.png top/Sdul_d23.png-003.png out.png
magick composite out.png Sdul.png out/Sdul_d23.png-003.png
magick composite bot/Sdul_d23.png-004.png mid/Sdul_d23.png-004.png out.png
magick composite out.png top/Sdul_d23.png-004.png out.png
magick composite out.png Sdul.png out/Sdul_d23.png-004.png
magick composite bot/Sdul_d23.png-005.png mid/Sdul_d23.png-005.png out.png
magick composite out.png top/Sdul_d23.png-005.png out.png
magick composite out.png Sdul.png out/Sdul_d23.png-005.png
magick composite bot/Sdul_d23.png.png mid/Sdul_d23.png.png out.png
magick composite out.png top/Sdul_d23.png.png out.png
magick composite out.png Sdul.png out/Sdul_d23.png.png
magick composite bot/Sdul_d24.png.png mid/Sdul_d24.png.png out.png
magick composite out.png top/Sdul_d24.png.png out.png
magick composite out.png Sdul.png out/Sdul_d24.png.png
magick composite bot/Sdul_d25.png.png mid/Sdul_d25.png.png out.png
magick composite out.png top/Sdul_d25.png.png out.png
magick composite out.png Sdul.png out/Sdul_d25.png.png
magick composite bot/Sdul_d26.png.png mid/Sdul_d26.png.png out.png
magick composite out.png top/Sdul_d26.png.png out.png
magick composite out.png Sdul.png out/Sdul_d26.png.png
magick composite bot/Sdul_e00.png.png mid/Sdul_e00.png.png out.png
magick composite out.png top/Sdul_e00.png.png out.png
magick composite out.png Sdul.png out/Sdul_e00.png.png
magick composite bot/Sdul_e01.png.png mid/Sdul_e01.png.png out.png
magick composite out.png top/Sdul_e01.png.png out.png
magick composite out.png Sdul.png out/Sdul_e01.png.png
magick composite bot/Sdul_e02.png.png mid/Sdul_e02.png.png out.png
magick composite out.png top/Sdul_e02.png.png out.png
magick composite out.png Sdul.png out/Sdul_e02.png.png
magick composite bot/Sdul_e03.png.png mid/Sdul_e03.png.png out.png
magick composite out.png top/Sdul_e03.png.png out.png
magick composite out.png Sdul.png out/Sdul_e03.png.png
magick composite bot/Sdul_f00.png.png mid/Sdul_f00.png.png out.png
magick composite out.png top/Sdul_f00.png.png out.png
magick composite out.png Sdul.png out/Sdul_f00.png.png
magick composite bot/Sdul_f01.png.png mid/Sdul_f01.png.png out.png
magick composite out.png top/Sdul_f01.png.png out.png
magick composite out.png Sdul.png out/Sdul_f01.png.png
magick composite bot/Sdul_f02.png.png mid/Sdul_f02.png.png out.png
magick composite out.png top/Sdul_f02.png.png out.png
magick composite out.png Sdul.png out/Sdul_f02.png.png
magick composite bot/Sdul_f03.png.png mid/Sdul_f03.png.png out.png
magick composite out.png top/Sdul_f03.png.png out.png
magick composite out.png Sdul.png out/Sdul_f03.png.png
magick composite bot/Sdul_f04.png.png mid/Sdul_f04.png.png out.png
magick composite out.png top/Sdul_f04.png.png out.png
magick composite out.png Sdul.png out/Sdul_f04.png.png
magick composite bot/Sdul_f05.png.png mid/Sdul_f05.png.png out.png
magick composite out.png top/Sdul_f05.png.png out.png
magick composite out.png Sdul.png out/Sdul_f05.png.png
